// Scribd Handler Module for DocCleaner & PDF Downloader
// Handles Scribd-specific ad removal, DOM unblurring, lazy-load auto-scrolling, and clean isolated PDF export.

(function () {
    'use strict';

    // List of CSS selectors targeting Scribd ads, promos, paywalls, and popups
    const SCRIBD_AD_SELECTORS = [
        '.promo_wrapper',
        '.promo_border',
        '.auto__doc_page_webpack_app_page_truncate_promo',
        '.auto__doc_page_webpack_doc_page_blur_promo',
        '.page_blur_promo',
        '.page-blur-promo',
        '.absolute_blur',
        '.autogenerated_promo',
        '.mobile_sticky_promo',
        '.sticky_archive_bar',
        '.page_blur_promo_wrapper',
        '.page_missing_explanation',
        '.between_page_portal_root',
        '[class*="PromoBanner"]',
        '[class*="AdWrapper"]',
        '[class*="MobileAppBanner"]',
        '[class*="modal_backdrop"]',
        '[class*="ModalBackdrop"]',
        '[class*="paywall_overlay"]',
        '[class*="PaywallOverlay"]',
        '[class*="BlurOverlay"]',
        '.promo_wrapper [class*="Button"]',
        '[class*="PromoBanner"] [class*="Button"]',
        '#credential_picker_container',
        '#credential_picker_iframe',
        'iframe[src*="accounts.google.com/gsi"]',
        'iframe[id*="credential_picker"]',
        '[id*="google-one-tap"]',
        'iframe[src*="google"]',
        'iframe[src*="doubleclick"]',
        'iframe[src*="adnxs"]',
        'div[id*="google_ads"]',
        'div[class*="google-ad"]',
        'div[class*="ad_wrapper"]',
        'div[class*="adsbygoogle"]'
    ];

    /**
     * Removes all Scribd ad elements and paywall overlays from the DOM
     */
    function removeScribdAds() {
        SCRIBD_AD_SELECTORS.forEach(selector => {
            document.querySelectorAll(selector).forEach(el => {
                try {
                    el.remove();
                } catch (e) {
                    el.style.display = 'none';
                }
            });
        });

        // Unblur page containers
        document.querySelectorAll('.outer_page, .document_page, .blurred_page').forEach(page => {
            page.style.filter = 'none';
            page.style.webkitFilter = 'none';
            page.style.opacity = '1';
            page.style.visibility = 'visible';
            page.classList.remove('blurred_page');
        });

        // Clear text blur shadows and unblur text layers without altering coordinates
        document.querySelectorAll('.text_layer, .text-layer').forEach(tl => {
            tl.style.filter = 'none';
            tl.style.webkitFilter = 'none';
        });

        document.querySelectorAll('.text_layer span, .text-layer span, [class^="ff"] span').forEach(el => {
            el.style.filter = 'none';
            el.style.webkitFilter = 'none';
            el.style.textShadow = 'none';
        });

        // Unblur document images
        document.querySelectorAll('.outer_page img, .document_page img').forEach(img => {
            img.style.filter = 'none';
            img.style.webkitFilter = 'none';
            img.style.opacity = '1';
        });

        // Hide watermarks & blur overlays
        document.querySelectorAll('[class*="Watermark"], [class*="watermark"], .watermark_overlay, .blur_overlay, .abs_blur')
            .forEach(el => {
                try {
                    el.remove();
                } catch (e) {
                    el.style.display = 'none';
                }
            });

        // Ensure sidebar and recommendation links ("You might also like") are interactive
        document.querySelectorAll('aside, [class*="sidebar"], [class*="Sidebar"], .right_column, .document_sidebar, [class*="recommendation"], [class*="Recommendation"]').forEach(sb => {
            sb.style.pointerEvents = 'auto';
        });
        document.querySelectorAll('aside a, aside button, [class*="sidebar"] a, [class*="sidebar"] button, [class*="Sidebar"] a, [class*="Sidebar"] button, .right_column a, .right_column button, .document_sidebar a, .document_sidebar button, [class*="recommendation"] a, [class*="recommendation"] button, [class*="Recommendation"] a, [class*="Recommendation"] button').forEach(link => {
            link.style.pointerEvents = 'auto';
            link.style.cursor = 'pointer';
        });

        // Restore body scrolling & text selection
        if (document.body) {
            document.body.style.overflow = 'auto';
            document.body.style.height = 'auto';
            document.body.style.userSelect = 'text';
            document.body.style.webkitUserSelect = 'text';
        }
    }

    /**
     * Initializes MutationObserver with debounce to continuously strip newly injected ads & popups
     */
    let cleanDebounceTimer = null;
    function initScribdAdBlocker() {
        removeScribdAds();

        const observer = new MutationObserver((mutations) => {
            let shouldClean = false;
            for (const mutation of mutations) {
                // Ignore mutations caused by our own Clean Viewer or FAB button
                if (mutation.target && (
                    mutation.target.id === 'clean-viewer-container' ||
                    mutation.target.id === 'studocu-fab-btn' ||
                    (mutation.target.closest && (mutation.target.closest('#clean-viewer-container') || mutation.target.closest('#studocu-fab-btn')))
                )) {
                    continue;
                }
                if (mutation.addedNodes.length > 0) {
                    shouldClean = true;
                    break;
                }
            }
            if (shouldClean) {
                if (cleanDebounceTimer) clearTimeout(cleanDebounceTimer);
                cleanDebounceTimer = setTimeout(removeScribdAds, 150);
            }
        });

        const target = document.body || document.documentElement;
        if (target) {
            observer.observe(target, { childList: true, subtree: true });
        } else {
            document.addEventListener('DOMContentLoaded', () => {
                observer.observe(document.body || document.documentElement, { childList: true, subtree: true });
            });
        }
    }

    /**
     * Creates a high-end, full-screen background progress overlay so the user never
     * sees any visible page scrolling or flickering during preloading.
     */
    function showPreloadOverlay(isVi) {
        const existing = document.getElementById('scribd-preload-overlay');
        if (existing) {
            try { existing.remove(); } catch (e) {}
        }

        const overlay = document.createElement('div');
        overlay.id = 'scribd-preload-overlay';
        overlay.style.cssText = `
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            width: 100vw !important;
            height: 100vh !important;
            background: rgba(9, 27, 66, 0.94) !important;
            backdrop-filter: blur(14px) !important;
            -webkit-backdrop-filter: blur(14px) !important;
            z-index: 2147483647 !important;
            display: flex !important;
            align-items: center !important;
            justify-content: center !important;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;
            color: #f6f7ef !important;
            user-select: none !important;
            opacity: 0;
            transition: opacity 0.25s ease !important;
        `;

        overlay.innerHTML = `
            <div style="
                background: #11224d;
                border: 1.5px solid rgba(255, 255, 255, 0.15);
                border-radius: 20px;
                padding: 32px 36px;
                max-width: 440px;
                width: 90%;
                text-align: center;
                box-shadow: 0 24px 60px rgba(0, 0, 0, 0.55), 0 0 35px rgba(88, 196, 116, 0.2);
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 16px;
            ">
                <div style="
                    width: 56px;
                    height: 56px;
                    border-radius: 18px;
                    background: rgba(88, 196, 116, 0.15);
                    border: 1px solid rgba(88, 196, 116, 0.35);
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    color: #58c474;
                ">
                    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.8" stroke-linecap="round" style="animation: scribdSpin 0.9s linear infinite;">
                        <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-opacity="0.25" stroke-width="2.8" fill="none"></circle>
                        <path d="M12 3a9 9 0 0 1 9 9" stroke="currentColor" stroke-width="2.8" fill="none"></path>
                    </svg>
                </div>

                <div>
                    <h3 style="margin: 0; font-size: 17.5px; font-weight: 700; color: #ffffff; letter-spacing: -0.2px;">
                        ${isVi ? 'Đang chuẩn bị PDF Scribd HD' : 'Preparing Scribd HD PDF'}
                    </h3>
                    <p id="scribd-preload-subtitle" style="margin: 6px 0 0 0; font-size: 13px; color: rgba(246, 247, 239, 0.75); font-weight: 500;">
                        ${isVi ? 'Đang tự động nạp & làm nét nội dung ngầm...' : 'Automatically loading & enhancing pages in background...'}
                    </p>
                </div>

                <div style="width: 100%; background: rgba(255, 255, 255, 0.1); border-radius: 999px; height: 8px; overflow: hidden; margin-top: 4px;">
                    <div id="scribd-preload-bar" style="width: 5%; height: 100%; background: linear-gradient(90deg, #58c474, #73e691); border-radius: 999px; transition: width 0.12s ease;"></div>
                </div>

                <div style="display: flex; justify-content: space-between; width: 100%; font-size: 12px; color: rgba(246, 247, 239, 0.65); font-weight: 600;">
                    <span id="scribd-preload-percent">5%</span>
                    <span id="scribd-preload-count">${isVi ? 'Đang xử lý...' : 'Processing...'}</span>
                </div>

                <div style="font-size: 11.5px; color: rgba(246, 247, 239, 0.45); margin-top: 2px;">
                    ${isVi ? '⚡ Không cần cuộn chuột — hệ thống tự nạp 100% trang' : '⚡ No manual scrolling needed — auto-loads 100% pages'}
                </div>
            </div>
            <style>
                @keyframes scribdSpin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
            </style>
        `;

        document.body.appendChild(overlay);
        requestAnimationFrame(() => {
            overlay.style.opacity = '1';
        });

        return {
            update(percent, current, total, customMsg) {
                const bar = document.getElementById('scribd-preload-bar');
                const pct = document.getElementById('scribd-preload-percent');
                const cnt = document.getElementById('scribd-preload-count');
                const sub = document.getElementById('scribd-preload-subtitle');

                const clamped = Math.min(100, Math.max(0, Math.round(percent)));
                if (bar) bar.style.width = clamped + '%';
                if (pct) pct.textContent = clamped + '%';
                if (cnt && total) {
                    cnt.textContent = isVi ? `Trang ${current || 1}/${total}` : `Page ${current || 1}/${total}`;
                }
                if (sub) {
                    if (customMsg) {
                        sub.textContent = customMsg;
                    } else if (clamped >= 88) {
                        sub.textContent = isVi ? 'Đang trích xuất đồ họa HD & chuẩn bị in...' : 'Extracting HD graphics & preparing print...';
                    }
                }
            },
            remove() {
                overlay.style.opacity = '0';
                setTimeout(() => {
                    try { overlay.remove(); } catch (e) {}
                }, 220);
            }
        };
    }

    /**
     * Fast, invisible programmatic preloader for Scribd.
     * Uses instant scrolling (behavior: 'instant') behind the overlay to trigger
     * IntersectionObservers rapidly so that Scribd creates DOM nodes for all pages.
     */
    async function preloadAllScribdPages(onProgress, overlayUI, isVi) {
        return new Promise(async (resolve) => {
            const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

            // Eagerly trigger any lazy images that have data-src
            document.querySelectorAll('.outer_page img, .document_page img').forEach((img) => {
                if (img.dataset) {
                    if (img.dataset.src && !img.src) img.src = img.dataset.src;
                    if (img.dataset.orig && (!img.src || img.src.includes('lowres'))) img.src = img.dataset.orig;
                }
                img.loading = 'eager';
                img.setAttribute('loading', 'eager');
            });

            // High-speed programmatic scroll pass
            const viewportHeight = window.innerHeight || 800;
            const scrollStep = Math.floor(viewportHeight * 1.5);
            let currentScroll = 0;
            let lastScrollHeight = 0;
            let sameHeightChecks = 0;

            while (true) {
                const totalHeight = Math.max(
                    document.documentElement.scrollHeight,
                    document.body.scrollHeight
                );

                currentScroll += scrollStep;
                window.scrollTo({ top: currentScroll, behavior: 'instant' });
                removeScribdAds();

                // Count pages currently in DOM
                const currentPages = document.querySelectorAll('.outer_page, .document_page, div[id^="outer_page_"]');
                const pageCount = currentPages.length || 1;
                const progress = Math.min(45, 5 + Math.floor((currentScroll / totalHeight) * 40));

                if (typeof onProgress === 'function') onProgress(progress);
                if (overlayUI) overlayUI.update(progress, Math.floor((progress / 45) * pageCount), pageCount, isVi ? 'Đang kích hoạt nạp ngầm các trang...' : 'Activating page containers...');

                if (currentScroll >= totalHeight) {
                    if (totalHeight === lastScrollHeight) {
                        sameHeightChecks++;
                    } else {
                        sameHeightChecks = 0;
                        lastScrollHeight = totalHeight;
                    }

                    // Bottom reached and height settled
                    if (sameHeightChecks >= 2) {
                        break;
                    }
                }

                await sleep(15);
            }

            resolve();
        });
    }

    /**
     * Checks if a Scribd page has finished rendering text spans, canvas, and images.
     */
    function isScribdPageRendered(page) {
        if (!page) return false;
        const textSpans = page.querySelectorAll('.text_layer span, .text-layer span, [class^="ff"] span, span');
        const imgs = Array.from(page.querySelectorAll('img'));
        const canvases = Array.from(page.querySelectorAll('canvas'));

        const imgsReady = imgs.length === 0 || imgs.every(img => (img.complete && img.naturalWidth > 0) || img.getAttribute('src')?.startsWith('data:'));
        const canvasesReady = canvases.length === 0 || canvases.every(c => c.width > 0 && c.height > 0);
        const textReady = textSpans.length > 0 || page.innerHTML.length > 300;

        return imgsReady && canvasesReady && textReady;
    }

    /**
     * True Page Readiness Detection for Scribd:
     * Waits until the page's images, canvas, and text layer are completely stable and rendered.
     */
    function waitForScribdPageReady(page) {
        return new Promise((resolve) => {
            let lastLen = -1;
            let stable = 0;
            let tries = 0;

            // Trigger lazy images eagerly
            page.querySelectorAll('img').forEach(img => {
                if (img.dataset) {
                    if (img.dataset.src && !img.src) img.src = img.dataset.src;
                    if (img.dataset.orig && (!img.src || img.src.includes('lowres'))) img.src = img.dataset.orig;
                }
                img.setAttribute('loading', 'eager');
                img.loading = 'eager';
            });

            function check() {
                const len = page.innerHTML.length;
                if (isScribdPageRendered(page)) {
                    if (len === lastLen) {
                        stable++;
                    } else {
                        stable = 0;
                        lastLen = len;
                    }
                    if (stable >= 2) {
                        resolve();
                        return;
                    }
                }
                if (tries++ > 15) { // max ~1.5s per page
                    resolve();
                    return;
                }
                setTimeout(check, 100);
            }
            check();
        });
    }

    /**
     * Embeds all image URLs as Data URIs (Base64) into RAM.
     * Guarantees 100% print preview reliability without missing assets, blank images, or broken tables.
     */
    async function embedImagesAsDataUris(pagesList, onProgress) {
        const urls = [];
        const urlMap = {};

        pagesList.forEach(p => {
            p.querySelectorAll('img').forEach(img => {
                let src = img.getAttribute('src');
                if (!src && img.dataset && img.dataset.src) {
                    src = img.dataset.src;
                    img.setAttribute('src', src);
                    img.src = src;
                }
                if (src && src.startsWith('http') && !urls.includes(src)) {
                    urls.push(src);
                }
            });
        });

        if (urls.length === 0) return;

        let completed = 0;
        const CONCURRENCY = 6;
        let nextIdx = 0;

        async function worker() {
            while (nextIdx < urls.length) {
                const url = urls[nextIdx++];
                try {
                    const res = await fetch(url, { credentials: 'omit' });
                    if (res.ok) {
                        const blob = await res.blob();
                        if (blob && blob.size > 0) {
                            const dataUri = await new Promise((resolve) => {
                                const reader = new FileReader();
                                reader.onload = () => resolve(reader.result);
                                reader.onerror = () => resolve(null);
                                reader.readAsDataURL(blob);
                            });
                            if (dataUri) {
                                urlMap[url] = dataUri;
                            }
                        }
                    }
                } catch (err) {}
                completed++;
                if (typeof onProgress === 'function') {
                    onProgress(completed, urls.length);
                }
            }
        }

        const workers = [];
        for (let c = 0; c < Math.min(CONCURRENCY, urls.length); c++) {
            workers.push(worker());
        }
        await Promise.all(workers);

        // Replace img src attributes with Data URIs
        pagesList.forEach(p => {
            p.querySelectorAll('img').forEach(img => {
                const s = img.getAttribute('src');
                if (urlMap[s]) {
                    img.setAttribute('src', urlMap[s]);
                    img.src = urlMap[s];
                }
            });
        });
    }

    /**
     * Main action executed when clicking "Tải PDF HD" on Scribd
     */
    async function runScribdCleaner(statusCallback) {
        const updateStatus = (msg) => {
            if (typeof statusCallback === 'function') statusCallback(msg);
        };

        let isVi = false;
        try {
            if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
                const { lang } = await chrome.storage.local.get({ lang: 'en' });
                isVi = lang === 'vi';
            }
        } catch (e) {}

        const initialScrollY = window.scrollY;
        let overlayUI = null;

        try {
            updateStatus(isVi ? 'Đang chuẩn bị...' : 'Preparing...');
            removeScribdAds();

            let pages = document.querySelectorAll('.outer_page, .document_page, div[id^="outer_page_"]');
            if (pages.length === 0) {
                pages = document.querySelectorAll('div[data-page-number], div[data-page-index], .page_container');
            }

            if (pages.length === 0) {
                alert(isVi ? 'Không tìm thấy trang tài liệu nào trên Scribd.\n(Vui lòng mở một trang đọc tài liệu Scribd để xuất PDF!)' : 'No document pages found on Scribd.\n(Please open a document page on Scribd to export PDF!)');
                return;
            }

            // Show sleek fullscreen progress overlay so user never sees page scrolling
            overlayUI = showPreloadOverlay(isVi);
            overlayUI.update(5, 1, pages.length, isVi ? 'Đang quét & kích hoạt trang ngầm...' : 'Scanning & activating pages...');

            // Step 1: Fast scroll pass to ensure Scribd injects all page containers into the DOM
            updateStatus(isVi ? 'Đang kích hoạt toàn bộ trang...' : 'Activating all pages...');
            await preloadAllScribdPages((percent) => {
                updateStatus(isVi ? `Đang nạp trang... ${percent}%` : `Loading pages... ${percent}%`);
            }, overlayUI, isVi);

            // Re-query pages after lazy loading
            pages = document.querySelectorAll('.outer_page, .document_page, div[id^="outer_page_"]');
            if (pages.length === 0) {
                pages = document.querySelectorAll('div[data-page-number], div[data-page-index], .page_container');
            }

            const totalPages = pages.length;
            const capturedPages = [];

            // Step 2: Targeted page-by-page readiness check & deep capture
            for (let i = 0; i < totalPages; i++) {
                const page = pages[i];
                if (page) {
                    page.scrollIntoView({ behavior: 'instant', block: 'center' });
                    window.dispatchEvent(new Event('scroll', { bubbles: true }));
                }

                // Wait until page text, images, and canvas are 100% loaded
                await waitForScribdPageReady(page);

                const pageStyle = window.getComputedStyle(page);
                const rect = page.getBoundingClientRect();
                const width = parseFloat(pageStyle.width) || rect.width || 800;
                const height = parseFloat(pageStyle.height) || rect.height || 1050;

                const cleanPage = document.createElement('div');
                cleanPage.className = 'scribd-clean-page';
                cleanPage.id = `scribd-page-${i + 1}`;
                cleanPage.style.width = width + 'px';
                cleanPage.style.height = height + 'px';

                const clone = page.cloneNode(true);

                // Strip ad/promo banners inside clone
                clone.querySelectorAll(SCRIBD_AD_SELECTORS.join(',')).forEach(el => {
                    try { el.remove(); } catch (e) {}
                });

                // Convert Canvas to High-Res Image (or drawImage) for 100% print preview reliability
                const origCanvases = page.querySelectorAll('canvas');
                const cloneCanvases = clone.querySelectorAll('canvas');
                origCanvases.forEach((origCanvas, ci) => {
                    const cloneCanvas = cloneCanvases[ci];
                    if (cloneCanvas && origCanvas.width > 0 && origCanvas.height > 0) {
                        try {
                            const dataUrl = origCanvas.toDataURL('image/png');
                            if (dataUrl && dataUrl.startsWith('data:image')) {
                                const canvasImg = document.createElement('img');
                                canvasImg.src = dataUrl;
                                canvasImg.className = cloneCanvas.className;
                                canvasImg.style.cssText = cloneCanvas.style.cssText;
                                if (origCanvas.style.width) canvasImg.style.width = origCanvas.style.width;
                                if (origCanvas.style.height) canvasImg.style.height = origCanvas.style.height;
                                canvasImg.style.display = 'block';
                                canvasImg.style.visibility = 'visible';
                                canvasImg.style.opacity = '1';
                                cloneCanvas.parentNode.replaceChild(canvasImg, cloneCanvas);
                            } else {
                                cloneCanvas.width = origCanvas.width;
                                cloneCanvas.height = origCanvas.height;
                                const ctx = cloneCanvas.getContext('2d');
                                if (ctx) ctx.drawImage(origCanvas, 0, 0);
                            }
                        } catch (e) {
                            cloneCanvas.width = origCanvas.width;
                            cloneCanvas.height = origCanvas.height;
                            const ctx = cloneCanvas.getContext('2d');
                            if (ctx) {
                                try { ctx.drawImage(origCanvas, 0, 0); } catch (err) {}
                            }
                        }
                    }
                });

                // Ensure clone root container matches original size and coordinate space
                clone.style.width = width + 'px';
                clone.style.height = height + 'px';
                clone.style.position = 'relative';
                clone.style.top = '0';
                clone.style.left = '0';
                clone.style.margin = '0';
                clone.style.display = 'block';
                clone.style.visibility = 'visible';
                clone.style.opacity = '1';
                clone.style.filter = 'none';
                clone.style.webkitFilter = 'none';
                clone.classList.remove('blurred_page');

                // Ensure images are unblurred and loaded eagerly
                clone.querySelectorAll('img').forEach(img => {
                    if (img.dataset) {
                        if (img.dataset.src && !img.src) img.src = img.dataset.src;
                        if (img.dataset.orig && (!img.src || img.src.includes('lowres'))) img.src = img.dataset.orig;
                    }
                    img.setAttribute('loading', 'eager');
                    img.loading = 'eager';
                    img.style.filter = 'none';
                    img.style.webkitFilter = 'none';
                    img.style.opacity = '1';
                    img.style.visibility = 'visible';
                });

                // Remove blur and text shadows on text layers without modifying positioning coordinates
                clone.querySelectorAll('.text_layer, .text-layer').forEach(tl => {
                    tl.style.filter = 'none';
                    tl.style.webkitFilter = 'none';
                });
                clone.querySelectorAll('.text_layer span, .text-layer span, [class^="ff"] span').forEach(span => {
                    span.style.filter = 'none';
                    span.style.webkitFilter = 'none';
                    span.style.textShadow = 'none';
                });

                // Preserve table formatting and borders
                clone.querySelectorAll('table').forEach(tbl => {
                    tbl.style.borderCollapse = 'collapse';
                    tbl.style.webkitPrintColorAdjust = 'exact';
                });

                cleanPage.appendChild(clone);
                capturedPages.push(cleanPage);

                const progress = 45 + Math.floor(((i + 1) / totalPages) * 30);
                overlayUI.update(
                    progress,
                    i + 1,
                    totalPages,
                    isVi ? `Đang nạp & tối ưu trang ${i + 1}/${totalPages}...` : `Optimizing page ${i + 1}/${totalPages}...`
                );
            }

            // Restore scroll position
            window.scrollTo({ top: initialScrollY, behavior: 'instant' });

            // Step 3: Embed All Images as Data URIs (Base64) to Guarantee 100% Print Reliability
            overlayUI.update(76, totalPages, totalPages, isVi ? 'Đang chuyển đổi & nhúng ảnh HD/bảng biểu vào RAM...' : 'Embedding HD images & tables into RAM...');

            await embedImagesAsDataUris(capturedPages, (done, total) => {
                const pct = 76 + Math.floor((done / total) * 20);
                overlayUI.update(
                    pct,
                    totalPages,
                    totalPages,
                    isVi ? `Đang nhúng ảnh & bảng biểu HD (${done}/${total})...` : `Embedding HD images & tables (${done}/${total})...`
                );
            });

            // Step 4: Assemble Clean Viewer Container
            const oldViewer = document.getElementById('clean-viewer-container');
            if (oldViewer) oldViewer.remove();

            const viewerContainer = document.createElement('div');
            viewerContainer.id = 'clean-viewer-container';

            capturedPages.forEach(cleanPage => {
                viewerContainer.appendChild(cleanPage);
            });

            // Inject isolated Clean Viewer styles
            const oldStyle = document.getElementById('clean-viewer-styles');
            if (oldStyle) oldStyle.remove();

            const viewerStyle = document.createElement('style');
            viewerStyle.id = 'clean-viewer-styles';
            viewerStyle.textContent = `
                body { 
                    background-color: #f6f7fb !important; 
                    margin: 0 !important; 
                    overflow: auto !important; 
                }
                body > *:not(#clean-viewer-container) { 
                    display: none !important; 
                }
                #clean-viewer-container {
                    position: absolute; 
                    top: 0; left: 0; 
                    width: 100%;
                    display: flex; 
                    flex-direction: column; 
                    align-items: center;
                    padding: 20px 0; 
                    z-index: 999999;
                    opacity: 1 !important;
                    visibility: visible !important;
                }
                .scribd-clean-page {
                    position: relative !important; 
                    background-color: white !important; 
                    box-shadow: 0 4px 15px rgba(0,0,0,0.1); 
                    margin-bottom: 20px;
                    overflow: hidden !important; 
                    display: block !important;
                }
                .scribd-clean-page table,
                .scribd-clean-page tr,
                .scribd-clean-page td,
                .scribd-clean-page th {
                    -webkit-print-color-adjust: exact !important;
                    print-color-adjust: exact !important;
                }
                .scribd-clean-page svg {
                    -webkit-print-color-adjust: exact !important;
                    print-color-adjust: exact !important;
                }
                @media print {
                    @page { 
                        margin: 0; 
                        size: auto; 
                    }
                    html, body { 
                        background-color: white !important; 
                        margin: 0 !important; 
                        padding: 0 !important; 
                        width: 100% !important; 
                        height: auto !important; 
                        overflow: visible !important; 
                        -webkit-print-color-adjust: exact; 
                        print-color-adjust: exact; 
                    }
                    #clean-viewer-container { 
                        position: static !important; 
                        display: block !important; 
                        width: 100% !important; 
                        padding: 0 !important; 
                        margin: 0 !important; 
                    }
                    .scribd-clean-page { 
                        position: relative !important; 
                        margin: 0 auto !important; 
                        padding: 0 !important; 
                        box-shadow: none !important; 
                        page-break-after: always !important; 
                        break-after: page !important; 
                        page-break-inside: avoid !important; 
                        break-inside: avoid !important; 
                        background: white !important; 
                        overflow: hidden !important; 
                    }
                    .scribd-clean-page:last-child {
                        page-break-after: auto !important;
                        break-after: auto !important;
                    }
                    .scribd-clean-page table,
                    .scribd-clean-page tr,
                    .scribd-clean-page td,
                    .scribd-clean-page th {
                        -webkit-print-color-adjust: exact !important;
                        print-color-adjust: exact !important;
                    }
                    .scribd-clean-page svg {
                        -webkit-print-color-adjust: exact !important;
                        print-color-adjust: exact !important;
                    }
                    .scribd-clean-page img,
                    .scribd-clean-page canvas {
                        display: block !important;
                        visibility: visible !important;
                        opacity: 1 !important;
                    }
                }
            `;
            document.head.appendChild(viewerStyle);
            document.body.appendChild(viewerContainer);

            overlayUI.update(98, totalPages, totalPages, isVi ? 'Đang mở hộp thoại in PDF...' : 'Opening print window...');
            await new Promise(r => setTimeout(r, 150));

            if (overlayUI) {
                overlayUI.remove();
            }

            updateStatus(isVi ? 'Đang mở cửa sổ in PDF...' : 'Opening print window...');
            setTimeout(() => {
                window.addEventListener('afterprint', cleanupAfterPrint, { once: true });
                window.print();
                setTimeout(cleanupAfterPrint, 2500);
            }, 500);
        } catch (err) {
            console.error('DocCleaner Scribd error:', err);
            if (overlayUI) overlayUI.remove();
            cleanupAfterPrint();
            alert('Error: ' + (err && err.message ? err.message : err));
        }
    }

    /**
     * Removes the clean viewer container, styles, and preload overlay
     * to restore the original page UI after printing.
     */
    function cleanupAfterPrint() {
        const viewer = document.getElementById('clean-viewer-container');
        const style = document.getElementById('clean-viewer-styles');
        const overlay = document.getElementById('scribd-preload-overlay');
        if (viewer) viewer.remove();
        if (style) style.remove();
        if (overlay) overlay.remove();
    }

    // Export functions to window scope for router in content.js
    window.initScribdAdBlocker = initScribdAdBlocker;
    window.runScribdCleaner = runScribdCleaner;
    window.removeScribdAds = removeScribdAds;
    window.cleanupAfterPrint = cleanupAfterPrint;
})();
