// Scribd Handler Module for DocCleaner & PDF Downloader
// Handles Scribd-specific ad removal, DOM unblurring, lazy-load auto-scrolling, and clean isolated PDF export.

(function () {
    'use strict';

    // List of CSS selectors targeting Scribd ads, promos, paywalls, and popups
    const SCRIBD_AD_SELECTORS = [
        '.promo_wrapper',
        '.promo_border',
        '.auto__doc_page_webpack_app_page_truncate_promo',
        '.page_blur_promo',
        '.absolute_blur',
        '.autogenerated_promo',
        '.mobile_sticky_promo',
        '.sticky_archive_bar',
        '.sidebar_spacer',
        '.scribd_doc_header',
        '.page_blur_promo_wrapper',
        '[class*="PromoBanner"]',
        '[class*="AdWrapper"]',
        '[class*="MobileAppBanner"]',
        '[class*="AccentButton-module_wrapper"]',
        '[class*="SecondaryButton-module_wrapper"]',
        'iframe[src*="google"]',
        'iframe[src*="doubleclick"]',
        'iframe[src*="adnxs"]',
        'div[id*="google_ads"]',
        'div[class*="google-ad"]',
        'div[class*="ad_wrapper"]',
        'div[class*="adsbygoogle"]'
    ];

    /**
     * Removes all Scribd ad elements and paywall overlays from the DOM
     */
    function removeScribdAds() {
        SCRIBD_AD_SELECTORS.forEach(selector => {
            document.querySelectorAll(selector).forEach(el => {
                try {
                    el.remove();
                } catch (e) {
                    el.style.display = 'none';
                }
            });
        });

        // Unblur text layers, outer pages, and remove watermark elements
        document.querySelectorAll('.outer_page, .document_page, .blurred_page, .text_layer, .text-layer').forEach(page => {
            page.style.filter = 'none';
            page.style.webkitFilter = 'none';
            page.style.opacity = '1';
            page.style.visibility = 'visible';
            page.classList.remove('blurred_page');
        });

        // Clear text blur shadows and restore full opacity on all text elements
        document.querySelectorAll('.text_layer *, .text-layer *, .outer_page span, .document_page span').forEach(el => {
            el.style.filter = 'none';
            el.style.webkitFilter = 'none';
            el.style.textShadow = 'none';
            el.style.opacity = '1';
            el.style.visibility = 'visible';
        });

        // Hide watermarks & blur overlays
        document.querySelectorAll('[class*="Watermark"], [class*="watermark"], .watermark_overlay, .blur_overlay, .abs_blur')
            .forEach(el => el.remove());

        // Restore body scrolling & text selection
        document.body.style.overflow = 'auto';
        document.body.style.height = 'auto';
        document.body.style.userSelect = 'text';
        document.body.style.webkitUserSelect = 'text';
    }

    /**
     * Initializes MutationObserver to continuously strip newly injected ads & popups
     */
    function initScribdAdBlocker() {
        removeScribdAds();

        const observer = new MutationObserver((mutations) => {
            let shouldClean = false;
            for (const mutation of mutations) {
                if (mutation.addedNodes.length > 0) {
                    shouldClean = true;
                    break;
                }
            }
            if (shouldClean) {
                removeScribdAds();
            }
        });

        if (document.body) {
            observer.observe(document.body, { childList: true, subtree: true });
        } else {
            document.addEventListener('DOMContentLoaded', () => {
                observer.observe(document.body, { childList: true, subtree: true });
            });
        }
    }

    /**
     * Auto-scrolls through the Scribd document to force lazy-loaded pages into DOM
     */
    async function preloadAllScribdPages(onProgress) {
        const totalHeight = document.documentElement.scrollHeight || document.body.scrollHeight;
        const viewportHeight = window.innerHeight;
        let currentScroll = 0;
        const step = Math.floor(viewportHeight * 0.85);

        return new Promise((resolve) => {
            const scrollInterval = setInterval(() => {
                currentScroll += step;
                window.scrollTo(0, currentScroll);

                // Unblur as we scroll
                removeScribdAds();

                const progress = Math.min(100, Math.floor((currentScroll / totalHeight) * 100));
                if (typeof onProgress === 'function') {
                    onProgress(progress);
                }

                if (currentScroll >= totalHeight) {
                    clearInterval(scrollInterval);
                    // Scroll back to top
                    window.scrollTo(0, 0);
                    setTimeout(resolve, 800); // Give browser time to finish image rendering
                }
            }, 80);
        });
    }

    /**
     * Main action executed when clicking "Tải PDF HD" on Scribd
     */
    async function runScribdCleaner(statusCallback) {
        const updateStatus = (msg) => {
            if (typeof statusCallback === 'function') statusCallback(msg);
        };

        let isVi = false;
        try {
            if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
                const { lang } = await chrome.storage.local.get({ lang: 'en' });
                isVi = lang === 'vi';
            }
        } catch (e) {}

        updateStatus(isVi ? 'Đang quét trang Scribd...' : 'Scanning Scribd pages...');
        removeScribdAds();

        const pages = document.querySelectorAll('.outer_page, .document_page');
        if (pages.length === 0) {
            alert(isVi ? 'Không tìm thấy trang tài liệu nào trên Scribd.\n(Vui lòng mở một trang đọc tài liệu Scribd để xuất PDF!)' : 'No document pages found on Scribd.\n(Please open a document page on Scribd to export PDF!)');
            return;
        }

        updateStatus(isVi ? 'Tải trước tất cả trang...' : 'Preloading all pages...');
        await preloadAllScribdPages((percent) => {
            updateStatus(isVi ? `Đang nạp trang... ${percent}%` : `Loading pages... ${percent}%`);
        });

        updateStatus(isVi ? 'Đang làm nét & tạo bộ xem sạch...' : 'Unblurring & rendering clean view...');
        removeScribdAds();

        // Build Clean Viewer Container to isolate document pages from Scribd UI header/sidebar
        const oldViewer = document.getElementById('clean-viewer-container');
        if (oldViewer) oldViewer.remove();

        const viewerContainer = document.createElement('div');
        viewerContainer.id = 'clean-viewer-container';

        pages.forEach((page, index) => {
            const cleanPage = document.createElement('div');
            cleanPage.className = 'scribd-clean-page';
            cleanPage.id = `scribd-page-${index + 1}`;

            const clone = page.cloneNode(true);

            // Strip any remaining promo banners inside the clone
            clone.querySelectorAll('.promo_wrapper, .promo_border, .auto__doc_page_webpack_app_page_truncate_promo, .page_blur_promo, .absolute_blur').forEach(el => el.remove());

            // Reset clone styling to force full visibility
            clone.style.display = 'block';
            clone.style.visibility = 'visible';
            clone.style.opacity = '1';
            clone.style.filter = 'none';
            clone.style.margin = '0 auto';
            clone.style.position = 'relative';
            clone.style.left = 'auto';
            clone.style.top = 'auto';

            // Ensure inner images and text spans are visible
            clone.querySelectorAll('img, span, div, canvas').forEach(el => {
                el.style.visibility = 'visible';
                el.style.opacity = '1';
                el.style.filter = 'none';
            });

            cleanPage.appendChild(clone);
            viewerContainer.appendChild(cleanPage);
        });

        // Inject isolated Clean Viewer styles
        const oldStyle = document.getElementById('clean-viewer-styles');
        if (oldStyle) oldStyle.remove();

        const viewerStyle = document.createElement('style');
        viewerStyle.id = 'clean-viewer-styles';
        viewerStyle.textContent = `
            body { 
                background-color: #f6f7fb !important; 
                margin: 0 !important; 
                overflow: auto !important; 
            }
            body > *:not(#clean-viewer-container) { 
                display: none !important; 
            }
            #clean-viewer-container {
                position: absolute; 
                top: 0; left: 0; 
                width: 100%;
                display: flex; 
                flex-direction: column; 
                align-items: center;
                padding: 20px 0; 
                z-index: 999999;
                opacity: 1 !important;
                visibility: visible !important;
            }
            .scribd-clean-page {
                position: relative !important; 
                background-color: white !important;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1); 
                margin-bottom: 20px;
                overflow: hidden !important; 
                display: flex !important;
                justify-content: center !important;
                align-items: center !important;
                width: 100% !important;
            }
            @media print {
                @page { 
                    margin: 0; 
                    size: A4 portrait; 
                }
                html, body { 
                    background-color: white !important; 
                    margin: 0 !important;
                    padding: 0 !important;
                    width: 100% !important;
                    height: auto !important;
                    overflow: visible !important;
                    -webkit-print-color-adjust: exact; 
                    print-color-adjust: exact; 
                }
                #clean-viewer-container { 
                    position: static !important; 
                    display: block !important;
                    width: 100% !important; 
                    padding: 0 !important; 
                    margin: 0 !important; 
                }
                .scribd-clean-page {
                    position: relative !important;
                    width: 100% !important;
                    height: 100vh !important;
                    display: flex !important;
                    align-items: center !important;
                    justify-content: center !important;
                    margin: 0 !important; 
                    padding: 0 !important;
                    box-shadow: none !important; 
                    page-break-after: always !important; 
                    break-after: page !important; 
                    page-break-inside: avoid !important;
                    break-inside: avoid !important;
                    background: white !important;
                }
                .scribd-clean-page > * {
                    margin: 0 auto !important;
                }
            }
        `;
        document.head.appendChild(viewerStyle);
        document.body.appendChild(viewerContainer);

        updateStatus('Đang mở cửa sổ in PDF...');
        setTimeout(() => {
            window.print();
        }, 600);
    }

    // Export functions to window scope for router in content.js
    window.initScribdAdBlocker = initScribdAdBlocker;
    window.runScribdCleaner = runScribdCleaner;
    window.removeScribdAds = removeScribdAds;
})();
